inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'spec/**/*'
  - 'node_modules/**/*'
  DisplayCopNames: true

# gemfileの順番チェック
Bundler/OrderedGems:
  Enabled: false

# ブロックの開始後に複数行のdo endブロックに改行があるかどうかをチェック
Layout/MultilineBlockLayout:
  Exclude:
  - 'spec/**/*_spec.rb'

# ソースコードの行の長さをチェックする(デフォルト:80)
Layout/LineLength:
  Enabled: false

# メソッドのABCサイズが設定された最大値を超えていないか
Metrics/AbcSize:
  Max: 25

# ブロックの長さが最大値を超えているかどうか
Metrics/BlockLength:
  Max: 30
  Exclude:
  - 'Gemfile'
  - 'config/**/*'
  - 'spec/**/*_spec.rb'

# クラスの長さが最大値を超えているか
Metrics/ClassLength:
  CountComments: false
  Max: 300

# 循環的複雑度(メソッドを通る直線的に独立したパスの数)
Metrics/CyclomaticComplexity:
  Max: 30

# 一行の長さは120字まで。コメントは制限しない
Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ["^ *# "]
  Exclude:
    - "db/migrate/*.rb"
    - "config/**/*"

# メソッドの行数
Metrics/MethodLength:
  CountComments: false
  Max: 30

# セッターやゲターにsetやgetがついてないか
Naming/AccessorMethodName:
  Exclude:
  - 'app/controllers/**/*'

# 日本語のコメント(英語以外のコメント)をチェック
Style/AsciiComments:
  Enabled: false

# 1行に複数ブロックが含まれているかチェック
Style/BlockDelimiters:
  Exclude:
  - 'spec/**/*_spec.rb'

# クラス内のクラス等を定義する際の形式チェック
Style/ClassAndModuleChildren:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# 文字列をfreeze(immutable)にするか
Style/FrozenStringLiteralComment:
  Enabled: false

# each_key, value, transform_keys, valueを使用する
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# if式が1行で収まるかチェック
Style/IfUnlessModifier:
  Enabled: false

# %i[]か[:~]かのチェック
Style/SymbolArray:
  Enabled: false

# whileやuntilが指定文字数以内に1行で収まっているか
Style/WhileUntilModifier:
  Enabled: false